### PR TITLE
Added dockerization and local development docs

### PR DESCRIPTION
**Pull request by J4yTr1n1ty**

### CODE REVIEW

**Comment by J4yTr1n1ty** [comment]
Thanks for the feedback. Yes, I'm using docker almost daily working on projects. What I would recommend is building two docker images and combining them using docker compose. If you'd like, I could explain in to you in vc at some point.

But the basics here:

You have 2 Docker files, one building an image called `valo-spectra-server` and a second one `valo-spectra-frontend`. These can be published like GitHub releases on the GitHub or docker registry, so everyone can pull down versioned images.

Then you are able to create a single docker compose file (also included in this pull request just for the server tho) which will define which image you'd like to use and run both services together with the current version published on the docker/GitHub registry.

Example compose file:

```yaml
---
services:
  server:
    image: username/valo-spectra-server@latest
    ports:
      - "5100:5100"
      - "5101:5101"
      - "5102:5102"
    volumes:
      - ./keys:/app/keys
  frontend:
    image: username/valo-spectra-frontend@latest
    ports:
      - "3000:80"
```

**Comment by J4yTr1n1ty** [comment]
Also added some of the workflows I recommended above

**Comment by J4yTr1n1ty** [comment]
The following is a working example of the docker compose stack with the full application and self generating self-signed keys in case none are provided:


```yml
---
services:
  server:
    image: "pjcjay/valo-spectra-server:latest"
    ports:
      - "5100:5100"
      - "5101:5101"
      - "5102:5102"
    volumes:
      - ./keys:/app/keys
  frontend:
    image: "pjcjay/valo-spectra-frontend:latest"
    ports:
      - "3000:80"
```

**Comment by J4yTr1n1ty** [comment]
Current known issues:
- You need to rebuild the docker image to change the endpoint to connect to since there's currently no way of loading this from environment variables or a configuration file
- SSL Errors because of self-signed certificate that's not trusted

**Comment by b4iterdev** [comment]
> Current known issues:
> 
> * You need to rebuild the docker image to change the endpoint to connect to, since there's currently no way of loading this from environment variables or a configuration file
> * SSL Errors because of self-signed certificate that's not trusted
> * No way to configure the keys accepted without rebuilding docker image

you can get around the SSL error by setting INSECURE="True". But idk if that is recommended tho

**Comment by J4yTr1n1ty** [comment]
> INSECURE="True"
This is what I'm doing in production right now with a reverse proxy that's encrypting everything

**Pull request merged**
